<?php
/**
 * Advanced SEO/LLM Dashboard
 * Provides a centralized view of all location SEO data
 * Shows manual values vs. fallback values
 *
 * @package Chroma_Excellence
 * @since 1.0.0
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

class Chroma_SEO_Dashboard
{
    /**
     * Initialize the dashboard
     */
    public function init()
    {
        add_action('admin_menu', [$this, 'register_menu_page']);
        add_action('admin_enqueue_scripts', [$this, 'enqueue_assets']);
    }

    /**
     * Register the menu page
     */
    public function register_menu_page()
    {
        add_submenu_page(
            'edit.php?post_type=location', // Parent slug (Locations menu)
            'SEO & LLM Data',              // Page title
            'SEO & LLM Data',              // Menu title
            'edit_posts',                  // Capability
            'chroma-seo-dashboard',        // Menu slug
            [$this, 'render_page']         // Callback
        );
    }

    /**
     * Enqueue assets
     */
    public function enqueue_assets($hook)
    {
        if ($hook !== 'location_page_chroma-seo-dashboard') {
            return;
        }

        // Simple inline styles for the dashboard
        wp_add_inline_style('common', '
			.chroma-seo-table { width: 100%; border-collapse: collapse; background: #fff; box-shadow: 0 1px 1px rgba(0,0,0,0.04); }
			.chroma-seo-table th, .chroma-seo-table td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e5e5; vertical-align: top; }
			.chroma-seo-table th { background: #f9f9f9; font-weight: 600; border-bottom: 2px solid #ddd; }
			.chroma-seo-table tr:hover { background: #fbfbfb; }
			.chroma-value-manual { color: #2271b1; font-weight: 500; }
			.chroma-value-fallback { color: #646970; font-style: italic; }
			.chroma-badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 11px; margin-right: 4px; }
			.chroma-badge-manual { background: #e6f6e6; color: #006600; border: 1px solid #b3e6b3; }
			.chroma-badge-auto { background: #f0f0f1; color: #646970; border: 1px solid #dcdcde; }
			.chroma-status-icon { font-size: 16px; margin-right: 5px; }
			.chroma-check { color: #00a32a; }
			.chroma-cross { color: #d63638; }
		');
    }

    /**
     * Render the dashboard page
     */
    public function render_page()
    {
        $locations = get_posts([
            'post_type' => 'location',
            'posts_per_page' => -1,
            'orderby' => 'title',
            'order' => 'ASC',
        ]);

        ?>
        <div class="wrap">
            <h1 class="wp-heading-inline">SEO & LLM Data Dashboard</h1>
            <p class="description">
                Overview of SEO/LLM data for all locations.
                <span class="chroma-badge chroma-badge-manual">Manual</span> values are set by you.
                <span class="chroma-badge chroma-badge-auto">Auto</span> values are generated by the system fallbacks.
            </p>

            <br>

            <table class="chroma-seo-table widefat fixed striped">
                <thead>
                    <tr>
                        <th style="width: 200px;">Location</th>
                        <th>Service Area (Geo)</th>
                        <th>LLM Context</th>
                        <th>Quality & Ratings</th>
                        <th>Media & Pricing</th>
                        <th>Events & Enrollment</th>
                        <th style="width: 80px;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($locations as $location):
                        $id = $location->ID;

                        // Service Area Data
                        $geo_manual = get_post_meta($id, 'seo_llm_service_area_lat', true);
                        $geo_data = Chroma_Fallback_Resolver::get_service_area_circle($id);

                        // LLM Context
                        $intent_manual = get_post_meta($id, 'seo_llm_primary_intent', true);
                        $desc = Chroma_Fallback_Resolver::get_llm_description($id);

                        // Quality
                        $quality = get_post_meta($id, 'location_quality_rated', true);
                        $rating = get_post_meta($id, 'location_google_rating', true);

                        // Media/Pricing
                        $video = get_post_meta($id, 'location_video_tour_url', true);
                        $price = get_post_meta($id, 'location_price_min', true);

                        // Events/HowTo
                        $events = get_post_meta($id, 'location_events', true);
                        $howto = get_post_meta($id, 'location_enrollment_steps', true);
                        ?>
                        <tr>
                            <td>
                                <strong><a
                                        href="<?php echo get_edit_post_link($id); ?>"><?php echo get_the_title($id); ?></a></strong><br>
                                <small><?php echo get_post_meta($id, 'location_city', true); ?>,
                                    <?php echo get_post_meta($id, 'location_state', true); ?></small>
                            </td>

                            <td>
                                <?php if ($geo_manual): ?>
                                    <span class="chroma-badge chroma-badge-manual">Manual</span>
                                <?php else: ?>
                                    <span class="chroma-badge chroma-badge-auto">Auto</span>
                                <?php endif; ?>

                                <?php if ($geo_data): ?>
                                    <div><?php echo number_format($geo_data['lat'], 4); ?>,
                                        <?php echo number_format($geo_data['lng'], 4); ?>
                                    </div>
                                    <div>Radius: <?php echo $geo_data['radius']; ?> mi</div>
                                <?php else: ?>
                                    <span class="chroma-cross">×</span> No coordinates
                                <?php endif; ?>
                            </td>

                            <td>
                                <div style="margin-bottom: 6px;">
                                    <strong>Intent:</strong>
                                    <?php if ($intent_manual): ?>
                                        <span class="chroma-value-manual"><?php echo esc_html($intent_manual); ?></span>
                                    <?php else: ?>
                                        <span class="chroma-value-fallback">Childcare & Early Education</span>
                                    <?php endif; ?>
                                </div>
                                <div>
                                    <strong>Description:</strong>
                                    <div style="font-size: 11px; line-height: 1.4;">
                                        <?php echo wp_trim_words($desc, 15); ?>
                                    </div>
                                </div>
                            </td>

                            <td>
                                <div style="margin-bottom: 4px;">
                                    <?php if ($quality): ?>
                                        <span class="chroma-check">✓</span> Quality Rated
                                    <?php else: ?>
                                        <span class="chroma-cross">×</span> Not Rated
                                    <?php endif; ?>
                                </div>
                                <div>
                                    <?php if ($rating): ?>
                                        <span class="chroma-check">✓</span> Google: <?php echo esc_html($rating); ?>
                                    <?php else: ?>
                                        <span style="color: #ccc;">-</span> No Rating
                                    <?php endif; ?>
                                </div>
                            </td>

                            <td>
                                <div style="margin-bottom: 4px;">
                                    <?php if ($video): ?>
                                        <span class="chroma-check">✓</span> Video Tour
                                    <?php else: ?>
                                        <span class="chroma-cross">×</span> No Video
                                    <?php endif; ?>
                                </div>
                                <div>
                                    <?php if ($price): ?>
                                        <span class="chroma-check">✓</span> Pricing
                                    <?php else: ?>
                                        <span class="chroma-cross">×</span> No Price
                                    <?php endif; ?>
                                </div>
                            </td>

                            <td>
                                <div style="margin-bottom: 4px;">
                                    <?php if (!empty($events)): ?>
                                        <span class="chroma-check">✓</span> <?php echo count($events); ?> Events
                                    <?php else: ?>
                                        <span style="color: #ccc;">-</span> No Events
                                    <?php endif; ?>
                                </div>
                                <div>
                                    <?php if (!empty($howto)): ?>
                                        <span class="chroma-check">✓</span> Enrollment Steps
                                    <?php else: ?>
                                        <span class="chroma-cross">×</span> No Steps
                                    <?php endif; ?>
                                </div>
                            </td>

                            <td>
                                <a href="<?php echo get_edit_post_link($id); ?>" class="button button-small">Edit</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php
    }
}
