<?php

/**
 * Auto-generated keyword mapping from CSV
 */
return array(
    'service-areas-marietta-west-ga' => array('Kidazzle early learning academy', 'daycare near me', 'Kidazzle learning academy', 'top rated daycare near me', 'Kidazzle early learning academy of marietta', 'free pre k near me', 'pre school near me', 'daycares near me within 5 mi'),
    'service-areas-lawrenceville-ga' => array('Kidazzle early learning', 'Kidazzle early learning academy of lawrenceville', 'daycare in lawrenceville', 'Kidazzle', 'classes for 7 year olds near me', 'afterschool programs near me', 'preschool lawrenceville ga', 'classes for toddlers near me'),
    'service-areas-mcdonough-ga' => array('Kidazzle daycare', 'Kidazzle ellenwood', 'daycare mcdonough ga', 'affordable daycare near me', 'preschools near me', 'preschool mcdonough ga', 'childcare centers near me', 'daycare with positive reinforcement techniques'),
    'home' => array('Kidazzle early learning academy of lilburn', 'part time preschool near me', 'pre k graduation', 'chrome academy', 'best preschools near me', 'early learning center at terry mill photos', 'daycare near me that accepts caps', 'jumpstart early learning academy'),
    'service-areas-tyrone-ga' => array('daycares near me', 'daycare in fayetteville ga', 'preschool peachtree city ga', 'preschool in peachtree city', '2 year old school near me', 'child care facilities near me', 'daycare with stem programs', 'daycares in fayetteville ga'),
    'lilburn' => array('Kidazzle early learning academy satellite', 'Kidazzle lilburn', 'afterschool program 30047', 'child care center lilburn ga', 'Kidazzle early learning academy locations', '1st creative learning academy tucker', 'day care near me within 1 mi', 'afterschool program lilburn ga'),
    'service-areas-pleasanthill-ga' => array('daycare duluth ga', 'early education near me', 'daycare duluth', 'daycare in duluth ga', 'childcare near me', 'daycare', 'an apple a day daycare', 'apple a day'),
    'service-areas-rivergreen-ga' => array('river green academy', 'Kidazzle early learning academy at jonesboro', 'rivergreen subdivision canton ga', 'daycare programs with learning', 'river green subdivision canton ga', 'christian preschool near me', 'part time daycare near me', 'river green academy reviews'),
    'service-areas-cherokee-ga' => array('daycares canton ga', 'half day daycare near me', 'private schools near me', 'cherokee academy', 'after school program canton', 'cherokee academy at clayton', 'pre school hiring near me', 'private schools in canton ga'),
    'service-areas-jonesboro-ga' => array('little creations learning center', 'daycares in statesboro georgia', 'montessori schools near me', 'free 3 year old preschool near me', 'school pick up service near me', 'god best learning academy and daycare', '3 year old preschool near me', 'bilingual montessori school'),
    'service-areas-satellite-ga' => array('preschool near me', 'daycare with camera access', '2660 satellite blvd duluth ga 30096', 'escuela de niños cerca de mi', 'bilingual daycare duluth ga', 'childcare duluth ga', 'gwinnett county pre k', 'little elly near me'),
    'service-areas-ellenwood-ga' => array('daycares near me that take infants', 'daycare in ellenwood ga', 'ellenwood ga to jonesboro ga', 'the learning station ellenwood', 'black owned daycares near me', 'daycares with cameras near me', 'the smart place ellenwood ga', 'morrow early learning center'),
    'service-areas-lilburn-ga' => array('daycares in lilburn ga', 'daycare stone mountain ga', 'after school matters number', 'daycare for children with dietary restrictions', 'daycares in snellville ga', 'pleasant hill daycare photographer', 'preschool near me within 0.5 mi', 'child education programs 30047'),
    'careers' => array('Kidazzle early learning academy duluth ga', 'eclc community learning center', 'early childhood education jobs', 'daycares near me with cameras', 'childcare career programs in macon ga', 'academy for early learners', 'duluth premier academy', 'exploring minds academy'),
    'post/piagets-sensorimotor-stage-how-babies-build-the-foundation-of-thinking' => array('solve', 'sensorimotor stages piaget', 'sensorimotor stages of development', 'sensorimotor stage in psychology', 'examples of the sensorimotor stage', 'sensorimotor stage substages', 'sensorimotor stage psychology definition', 'sensorimotor development piaget'),
    'post/b637f5ff-92a3-4b54-bb49-cd4bd23120a4-why-parent-involvement-shapes-curriculum-success-in-schools' => array('how parental involvement tools align with school curriculums', 'what is the reciprocal of a number', 'early childhood education parent involvement', 'what is a sample space in math', 'examples of combining like terms', 'how do you identify a parent function', 'how to read periodic table', 'outcome memories'),
    'service-areas-southcobb-ga' => array('creative learning preschool mableton ga', 'montessori school near me', 'childcare academy near me', 'premier learning early childhood education center', 'pre k and kindergarten schools near me', 'dreamplay learning center', 'daycares hiring near me no experience', 'montessori school atlanta'),
    'post/5-ways-alpharetta-parents-will-love-Kidazzle-early-learning-academy' => array('what part of the brain is problem solving'),
    'service-areas-midway-alpharetta-ga' => array('herring township childcare', 'preschools in bethany crossing', 'herring township preschools', 'alpharetta georgia daycare', 'midway early learning center', 'herring township day cares', 'bethany crossing child care', 'creme de la creme alpharetta'),
    'post/top-10-educational-toys-for-toddlers-that-promote-learning-and-fun' => array('toys for a 2-year-old boy', 'best 2 year old girl toys', 'best toys for 2 year old boy uk', 'best boy toys for 2 year old', 'best interactive toddler toys', 'toys for 21 month old boy', 'best christmas toys for 2 year old boy', 'popular toys for 2 year old girl'),
    'home-690714' => array('metro one learning academy', 'walk leap grow early learning center', 'preschool in wyndham farms', 'daycare powder springs', 'grow and glow daycare'),
    'post/from-wobbles-to-first-steps-how-babies-learn-to-walk' => array('stages of learning to walk', 'stages of walking'),
    'post/art-meets-math-finger-painting-for-learning' => array('example of rotation in math', 'form and movement in art examples', 'example of origin in math', 'kindergarten demo lesson ideas'),
    'post/the-best-educational-attractions-for-young-learners-in-ellenwood' => array('things to do in ellenwood ga'),
    'service-areas-roswell-ga' => array('personalized attention daycare', 'day care centers in roswell ga', 'jonesboro ga to roswell ga', 'the beacon at east roswell', 'beacon hill schools daycare', 'childcare in roswell', 'daycare roswell georgia', 'preschools in roswell'),
    'service-areas-marietta-east-ga' => array('praise el learning academy', 'marietta early learning center', 'bright horizons marietta ga', 'learning strategies for children marietta ga', '2960 shallowford rd marietta ga 30066', 'center for early education marietta', 'preschool east cobb', 'kiddie kollege east cobb'),
    'post/bilingual-daycare-unlocking-a-world-of-benefits-for-your-child' => array('cultural immersion in childcare benefits', 'benefits of bilingual nurseries for families from different backgrounds', 'bilingual nurseries benefits for children with no prior language exposure', 'benefits of bilingual nursery over traditional nursery'),
    'post/nurturing-diverse-learners-with-responsive-teaching-styles' => array('what is responsive teaching', 'responsive teaching strategies'),
    'post/what-to-do-if-kids-get-physical-during-a-meltdown' => array('squeezing toghtly when metling down'),
    'post/top-5-infant-friendly-parks-in-marietta-west-cobb-for-your-babys-first-outings' => array('places to take a 5 month old', 'places to go with a newborn', 'park for 1 year old near me', 'playgrounds for 1 year olds near me', 'where to take a 1 year old', 'baby parks near me for toddlers', 'places for babies to play', 'best toddler park near me'),
    'contact-us' => array('brooklet community church preschool'),
    'post/top-5-infant-friendly-parks-in-marietta-east-cobb-for-your-babys-first-outings' => array('east cobb park marietta ga', 'parks that offer the best variety for under-6 guests', 'parks with amenities for under-6 park days', 'playgrounds in marietta ga', 'baby free classes near me', 'toddler friendly parks near me', 'baby friendly parks near me', 'baby parks near me'),
    'post/the-words-you-use-and-the-behavior-you-give-your-child-matters' => array('10 phrases to use when your toddler doesn t listen', 'the way we speak to your child matters', 'what does revolution mean for kids', 'behavior words for kids', 'parenting advice'),
    'services-infant-care' => array('infant daycare san francisco', 'daycare center near me', 'cosmo child care'),
    'about-us' => array('reggio emilia preschool mableton', 'daycare near me with cameras', 'day care near me with cameras', 'early childhood education schools near me', 'what does stem in education stand for', 'rfm learning academy', 'early learning daycare', 'laura newman husband'),
    'services-pre-k-lottery' => array('preschool lottery near me', 'ellenwood ga to mcdonough ga', 'pre k in clayton county ga', 'georgia pre k lottery 2025', 'georgia preschool lottery', 'pre k lottery near me', 'lottery funded pre k', 'georgia pre k lottery'),
    'team' => array('academy of early learning', 'head of the class learning academy', 'Kidazzle early learning academy owner', 'courtney moultrie', 'discovery point canton'),
    'post/top-5-family-friendly-activities-near-marietta-ga-for-your-toddler' => array('activities for 2 year olds near me', 'toddler activities marietta ga', 'things to do with kids marietta ga', 'toddler activites'),
    'service-areas-johns-creek-ga' => array('private school in wyndham farms', 'montessori school alpharetta ga', 'Kidazzle early learning academy alpharetta ga', 'daycares in johns creek ga', 'preschool johns creek ga', 'johns creek preschool', '3000 old alabama road', 'daycare johns creek'),
    'post/top-5-infant-friendly-parks-in-johns-creek-for-your-babys-first-outings' => array('things to do with kids in johns creek ga', 'things to do with toddlers in johns creek', 'toddler activities johns creek', 'best playgrounds for babies', 'playground near me', 'johns creek playground', 'parks in johns creek ga', 'baby park'),
    'post/what-age-should-children-start-in-school' => array('when do people start school'),
    'tour-appointment' => array('la petite academy kenosha', 'mothers day out program near me', 'montessori daycares near me', 'weekend daycare near me', 'daycare open late', 'daycare prices near me', 'rainbow daycare near me', 'nature daycare near me'),
    'post/the-benefits-of-stem-toys-for-preschoolers' => array('benefits of stem toys for 5 year olds', 'benefits of stem toys for toddlers', 'benefits of stem toys for preschoolers', 'stem toys benefits for kids'),
    'acquisitions' => array('preschool franchise georgia', 'start a preschool franchise in georgia', 'austell day care centers for sale'),
    'programs' => array('how old is prodigy math game', 'daycares with camera', 'little Kidazzle'),
    'post/teaching-by-example-how-parents-shape-their-childrens-behavior' => array('how to solve division problems'),
    'post/types-of-daycare-centers-which-is-right-for-your-family' => array('different types of childcare', 'different types of daycare', 'types of daycare centers', 'types of daycares', 'types of daycare'),
    'post/4e325a73-d554-424b-8552-04cb2ee9653a-early-childhood-assessment-methods-explained' => array('anecdotal and running records are tools used in screening'),
    'post/4e52fe96-2ef8-48d8-88c7-5a45c9a7a7c0-what-to-inquire-during-a-daycare-tour-a-parents-comprehensive-checklist' => array('what to look for in a daycare tour'),
    'post/6e6e8eb0-dab6-49d1-b888-d42ed5b46816-budgeting-for-early-childhood-education-10-essential-steps' => array('cost-effective scheduling for early education'),
    'post/learning-the-different-body-parts-fun-ways-to-teach-young-children' => array('words that start with f for kids', 'teach parts of the body', 'teaching kids body parts', 'fattest kid in the world', 'how to teach body parts'),
    'post/the-5-best-daycares-for-potty-training-in-roswell-ga' => array('daycare with potty training programs'),
    'post/top-5-infant-friendly-parks-in-ellenwood-for-your-babys-first-outings' => array('parks in ellenwood georgia', 'parks in ellenwood ga', 'parks in ellenwood', 'park in ellenwood ga'),
    'post/da654b5c-b3b7-4751-adb7-6e8164ffd839-emotional-safety-in-learning-creating-environments-where-kids-feel-brave' => array('emotional safety in the classroom'),
    'post/detailed-reviews-of-the-top-10-birthday-party-services-in-marietta' => array('birthday party places marietta ga'),
    'post/signs-of-a-good-daycare' => array('signs of a good daycare', 'safe daycare', 'childcare signs'),
    'post/top-5-infant-friendly-parks-in-lilburn-for-your-babys-first-outings' => array('harmony grove park', 'parks for 1 year olds', 'parks for infants', 'parks in lilburn ga', 'baby playground', 'infant park', 'baby parks', 'parks in lilburn'),
    'post/buyers-guide-best-pediatricians-near-Kidazzle-academy-marietta-ga' => array('east cobb pediatricians'),
    'post/5-amazing-baby-boutiques-in-johns-creek-to-try-today' => array('baby store alpharetta'),
    'post/teaching-kids-how-to-blow-their-nose-building-healthy-habits-with-Kidazzle' => array('how to be a better kid'),
    'locations' => array('Kidazzle location'),
    'post/bringing-learning-to-life-through-interaction' => array('Kidazzleela'),
    'services-toddler-care' => array('m dot daycare'),
    'post/95a25d6a-fc73-47b6-8d41-92a5dec18211-the-psychology-behind-toy-throwing-understanding-your-childs-behavior' => array('toddler throws'),
);
